### ISSUE TITLE
OCL links to librtt-scripting/marshalling.so.2.8.0 instead of ...so.2.8

### ISSUE THREAD

**Issue by smits** [orocos-toolchain/ocl#31]
Shouldn't the components and executables link to the minor version of the plugins instead of the patch versions of the plugins as they do for liborocos-rtt? If they would we could do ABI compatible releases (patch nr increase) without having to recompile our entire toolchain and downstream packages.

**Comment by meyerj** [comment]
This should be solved by https://github.com/orocos-toolchain/rtt/pull/104, right?
