### ISSUE TITLE
this.require("service") segfault on 2.8 (14.04)

### ISSUE THREAD

**Issue by ahoarau** [orocos-toolchain/ocl#40]
This ops code causes a segfault : 
```python
import("rtt_rosdeployment")
this.require("rosdeployment")
```
Because the pointer passed to the plugin is null.
I'm okay with using ```loadService("Deployer","rosdeployment")``` but the Deployer's name can be changed and there's no ```this.getName()``` function available, so I'm lacking genericity.

> I tested also with a custom service, can't get the pointer to the deployer (always null)

> .provide rosdeployment works !

**Comment by ahoarau** [comment]
Fixed using :
```cpp
    boost::shared_ptr<MyService> Create(TaskContext* parent){
        shared_ptr sp(new MyService(parent));
        parent->provides()->addService( sp );
        return sp;
    }
ORO_SERVICE_NAMED_PLUGIN(MyService,"my_service")
```
as in [scripting](https://github.com/orocos-toolchain/rtt/blob/master/rtt/scripting/ScriptingService.cpp#L65).

I'll provide a PR for the ros_deployment service.

**Comment by meyerj** [comment]
The operation `require()` of the deployer is for loading services into the global service. `"rosdeployment"` cannot be loaded as a global service, but of course it should not segfault if instantiated without a parent TaskContext.

This issue/use case can be fixed at various places:

- orocos-toolchain/rtt#139 fixes the segfault and print an error message instead when a service plugin refuses to create an instance without a parent TaskContext (like in the ops example reported here)
- orocos-toolchain/ocl#42 adds the possibility to use the `this` keyword as an alias for the deployer itself in all operations that expect a string to identify a TaskContext.
- orocos-toolchain/rtt#136 by @ahoarau adds a `getName()` operation to the TaskContext interface which solves this issue indirectly by allowing to get the deployer's name as a string through that operation:

   ```
   loadService(getName(), "rosdeployment")
   ```
