### ISSUE TITLE
Doesn't build on OSX

### ISSUE THREAD

**Issue by colincsl** [orocos-toolchain/ocl#8]
readline is keg-only so it doesn't get installed to the normal system paths in OSX 10.9.

I added /usr/local/opt/readline to the CMAKE_PREFIX path and it worked.

**Comment by meyerj** [comment]
_For future reference:_ The creation of symlinks at `/usr/local` [can be enforced with](https://docs.brew.sh/FAQ#what-does-keg-only-mean)
```sh
brew link [--force] readline
```
which is what has been applied for Travis at https://github.com/orocos-toolchain/orocos_toolchain/pull/34, for example. Setting the `CMAKE_PREFIX_PATH` manually to the location where readline is installed is indeed another option.
