### ISSUE TITLE
log4cpp supported

### ISSUE THREAD

**Issue by ahoarau** [orocos-toolchain/ocl#82]
Is there any way to install log4cpp from debians (liblog4cpp-dev), or are there any advantages with using the orocos-toolchain-log4cpp ?
(Note that I can't compile OCL if the https://github.com/orocos-toolchain/log4cpp is not in the workspace)

**Comment by snrkiwi** [comment]
> On Feb 22, 2019, at 06:49, Antoine Hoarau <notifications@github.com> wrote:
> 
> Is there any way to install log4cpp from debians (liblog4cpp-dev), or are there any advantages with using the orocos-toolchain-log4cpp ?
> 

There are some custom differences between the upstream version and the version in Orocos. I don’t recall exactly what they are, but they’re to help with real-time support. We tried to get these into upstream several years back, but to no avail.

HTH
Stephen

**Comment by ahoarau** [comment]
Ok that makes sense. Closing then
